// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyhqqglcdokccdkizskh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5aHFxZ2xjZG9rY2Nka2l6c2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMTI0ODIsImV4cCI6MjA3ODc4ODQ4Mn0.rlchsq0WZ4pB7KvAHvLbuvCEVTwvjQsW0dJ47YjFdkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});